{
 "title": "Ultimate UNRAID Dashboard - Version 1.3",
 "description": "Developed by falconexe (Modified From Original Template by GilbN)",
 "tags": [
  "UNRAID",
  "Telegraf",
  "InfluxDB",
  "falconexe",
  "GilbN"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   { "name": "telegrafdatasource", "label": "Telegraf Datasource", "query": "influxdb" },
   { "name": "diskdatasource", "label": "Disk Datasource", "query": "influxdb" },
   { "name": "upsdatasource", "label": "UPS Datasource", "query": "influxdb" },
   {
    "name": "cputhreads",
    "label": "CPU Threads",
    "query": "SELECT last(\"n_cpus\") AS \"mean_n_cpus\" FROM \"system\"  WHERE (\"host\" =~ /^$host$/) "
   },
   {
    "name": "flashdrive",
    "label": "Set Flash (Boot) Drive",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   {
    "name": "cachedrives",
    "label": "Set Cache Drive(s)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   {
    "name": "paritydrives",
    "label": "Set Parity Drive(s)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   {
    "name": "arraydrives",
    "label": "Set Array Drive(s)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   { "name": "currency", "label": "Currency", "query": "$" },
   { "name": "upskwhprice", "label": "kWh Price" },
   {
    "name": "upsmaxwatt",
    "label": "UPS Max Output Power Capacity (Watt)"
   }
  ]
 },
 "panels": [
  {
   "title": "$host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "measurement": "system",
     "query": "SELECT sum(\"uptime\") FROM \"system\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Overwatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Array Storage Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Array Storage Total",
     "measurement": "disk",
     "query": "SELECT last(\"used\") AS \"Used\", last(\"free\") AS \"Free\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/user0' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  {
   "title": "Array Storage Utilized",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Array Storage Utilized",
     "measurement": "disk",
     "query": "SELECT last(\"used\") AS \"Used\", last(\"free\") AS \"Free\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/user0' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  {
   "title": "Array Storage Available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Array Storage Available",
     "measurement": "disk",
     "query": "SELECT last(\"used\") AS \"Used\", last(\"free\") AS \"Free\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/user0' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  {
   "title": "Array Storage Utilized %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Array Storage Utilized",
     "measurement": "disk",
     "query": "SELECT last(\"used\") AS \"Used\", last(\"free\") AS \"Free\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/user0' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  {
   "title": "Cache Storage Utilized",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Cache Storage Utilized",
     "measurement": "disk",
     "query": "SELECT last(\"used\") AS \"Used\", last(\"free\") AS \"Free\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/user0' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/cache" }
     ]
    }
   ]
  },
  {
   "title": "Cache Storage Utilized %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Cache Storage Utilized %",
     "measurement": "disk",
     "query": "SELECT last(\"used\") AS \"Used\", last(\"free\") AS \"Free\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/user0' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/cache" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "CPU Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM Free %",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "RAM Free %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAM Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Available",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAM Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "1GBe Network (eth0)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(last(\"bytes_recv\"), 1s) FROM \"net\" WHERE (\"host\" =~ /^$host$/ AND \"interface\" = 'eth0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "10GBe Network (eth2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth2" }
     ]
    },
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth2" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed Gauges",
   "type": "gauge",
   "description": "Note: Uses REGEX to Parse Fan Names From IPMI Sensor List!",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Fan 01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/fan./" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temps ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU 01 Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "cpu1_temp" }
     ]
    },
    {
     "alias": "CPU 02 Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "cpu2_temp" }
     ]
    }
   ]
  },
  { "title": "Array Growth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Array Growth (Day)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Day)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  {
   "title": "Array Growth (Week)",
   "type": "stat",
   "description": "Note: Query Options >  Min Interval - Must Match on Week/Month/Year (Set to 2h [2 Hours] by Default For Performance Reasons)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Week)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  {
   "title": "Array Growth (Month)",
   "type": "stat",
   "description": "Note: Query Options >  Min Interval - Must Match on Week/Month/Year (Set to 2h [2 Hours] by Default For Performance Reasons)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Month)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  {
   "title": "Array Growth (Annual)",
   "type": "stat",
   "description": "Note: Query Options >  Min Interval - Must Match on Week/Month/Year (Set to 2h [2 Hours] by Default For Performance Reasons)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Annual)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Docker CPU",
   "type": "graph",
   "description": "Note: Uses Variable",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $cputhreads" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Docker RAM",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Docker Network (Transmitted)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name TX",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Docker Network (Received)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name RX",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Flash I/O (Read & Write)",
   "type": "graph",
   "description": "Note: Uses Variable",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "Bps", "label": "Read" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ID_SERIAL", "operator": "=~", "value": "/^$flashdrive$/" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ID_SERIAL", "operator": "=~", "value": "/^$flashdrive$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache I/O (Read & Write)",
   "type": "graph",
   "description": "Note: Uses Variable",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "Bps", "label": "Read" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ID_SERIAL", "operator": "=~", "value": "/^$cachedrives$/" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ID_SERIAL", "operator": "=~", "value": "/^$cachedrives$/" }
     ]
    }
   ]
  },
  {
   "title": "Array I/O (Read)",
   "type": "graph",
   "description": "Note: Uses Variables | Use Overrides > Display Name to Dynamically Name Serial Number (Field Name) to Drive Number",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ID_SERIAL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ID_SERIAL" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ID_SERIAL", "operator": "=~", "value": "/^$arraydrives$/" },
      { "condition": "OR", "key": "ID_SERIAL", "operator": "=~", "value": "/^$paritydrives$/" }
     ]
    }
   ]
  },
  {
   "title": "Array I/O (Write)",
   "type": "graph",
   "description": "Note: Uses Variables | Use Overrides > Display Name to Dynamically Name Serial Number (Field Name) to Drive Number",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ID_SERIAL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ID_SERIAL" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ID_SERIAL", "operator": "=~", "value": "/^$arraydrives$/" },
      { "condition": "OR", "key": "ID_SERIAL", "operator": "=~", "value": "/^$paritydrives$/" }
     ]
    }
   ]
  },
  { "title": "Disk Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Array Disk Storage",
   "type": "table",
   "gridPos": { "h": 30, "w": 7, "x": 0, "y": 103 },
   "targets": [
    {
     "alias": "Disk 1",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/.*mnt|\\/var\\/lib\\/docker/" },
      {
       "condition": "AND",
       "key": "path",
       "operator": "!~",
       "value": "/\\/var\\/lib\\/docker\\/btrfs.*/"
      },
      { "condition": "AND", "key": "path", "operator": "<>", "value": "/rootfs/var/lib/docker" },
      { "condition": "AND", "key": "path", "operator": "!~", "value": "/rootfs*/" },
      { "condition": "AND", "key": "path", "operator": "<>", "value": "/var/lib/docker" },
      { "condition": "AND", "key": "fstype", "operator": "<>", "value": "rootfs" },
      { "condition": "AND", "key": "path", "operator": "<>", "value": "/mnt/user" },
      { "condition": "AND", "key": "path", "operator": "<>", "value": "/mnt/user0" },
      { "condition": "AND", "key": "path", "operator": "<>", "value": "/mnt/cache" }
     ]
    }
   ]
  },
  {
   "title": "Drive S.M.A.R.T. Health Overview",
   "type": "table",
   "description": "Note: Uses REGEX",
   "gridPos": { "h": 31, "w": 17, "x": 7, "y": 103 },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "serial_no" ], "type": "tag" },
      { "params": [ "fail" ], "type": "tag" },
      { "params": [ "flags" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp (C)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Temperature_Celsius" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "health_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Health OK?" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "udma_crc_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UDMA CRC Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Current Pending Sectors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Current_Pending_Sector" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reallocated Sectors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Reallocated_Sector_Ct" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reallocated Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Reallocated_Event_Count" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Offline/Uncorrectable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Offline_Uncorrectable" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power On Hours" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Power_On_Hours" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power Cycles" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Power_Cycle_Count" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Helium Level" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Helium_Level" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "Flash Storage",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 133 },
   "targets": [
    {
     "alias": "Disk 1",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Drive S.M.A.R.T. Health Summary",
   "type": "table",
   "description": "Parity, Array Drives, & Cache (31 Devices)",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 134 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "udma_crc_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UDMA CRC Errors" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Current Pending Sectors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reallocated Sectors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Reallocated_Sector_Ct" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reallocated Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Reallocated_Event_Count" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Offline/Uncorrectable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Offline_Uncorrectable" }
     ]
    }
   ]
  },
  {
   "title": "Cache Storage",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 137 },
   "targets": [
    {
     "alias": "Disk 1",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/cache" }
     ]
    }
   ]
  },
  {
   "title": "Array Storage",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 141 },
   "targets": [
    {
     "alias": "Disk 1",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" }
     ]
    }
   ]
  },
  {
   "title": "Drive Life",
   "type": "table",
   "description": "Parity, Array Drives, & Cache (31 Devices)",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 141 },
   "targets": [
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power On Hours" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Power_On_Hours" }
     ]
    }
   ]
  },
  {
   "title": "Drive Temperatures (Celsius)",
   "type": "graph",
   "description": "User Overrides > Display Name to Dynamically Name Serial Number (Field Name) to Drive Number",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_serial_no",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serial_no" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "serial_no", "operator": "!=", "value": "*" }
     ]
    }
   ]
  },
  { "title": "Detailed Server Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "Network Interfaces (RX)",
   "type": "graph",
   "description": "Note: Uses REGEX | Includes All Networks Interfaces (NICs, Bridges, Docker, & Virtual)",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "Network Interfaces (TX)",
   "type": "graph",
   "description": "Note: Uses REGEX | Includes All Networks Interfaces (NICs, Bridges, Docker, & Virtual)",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 169 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "Network 1GBe (eth0)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "Network 10GBe (eth2)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth2" }
     ]
    },
    {
     "alias": "Transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth2" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Buffered" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cached" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Package",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU 01",
   "type": "graph",
   "description": "Note: Uses REGEX To Find Cores in CPU 01. Change REGEX According to Your Number of Cores! Example: CPU 01 Has 8 Cores (16 With HyperThreading) - The REGEX For Cores 0-15 is \"/cpu(1[6-9]|2[0-9]|3[01])|cpu-total/\"",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "cpu",
       "operator": "!~",
       "value": "/cpu(1[6-9]|2[0-9]|3[01])|cpu-total/"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU 02",
   "type": "graph",
   "description": "Note: Uses REGEX To Find Cores in CPU 02. Change REGEX According to Your Number of Cores! Example: CPU 02 Has 8 Cores (16 With HyperThreading) - The REGEX For Cores 16-31 is \"/cpu(1[6-9]|2[0-9]|3[01])/\"",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 209 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/cpu(1[6-9]|2[0-9]|3[01])/" }
     ]
    }
   ]
  },
  {
   "title": "CPU 01 Core Load",
   "type": "bargauge",
   "description": "Note: Uses REGEX To Find Cores in CPU 01. Change REGEX According to Your Number of Cores! Example: CPU 01 Has 8 Cores (16 With HyperThreading) - The REGEX For Cores 0-15 is \"/cpu(1[6-9]|2[0-9]|3[01])|cpu-total/\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "cpu",
       "operator": "!~",
       "value": "/cpu(1[6-9]|2[0-9]|3[01])|cpu-total/"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU 02 Core Load",
   "type": "bargauge",
   "description": "Note: Uses REGEX To Find Cores in CPU 02. Change REGEX According to Your Number of Cores! Example: CPU 02 Has 8 Cores (16 With HyperThreading) - The REGEX For Cores 16-31 is \"/cpu(1[6-9]|2[0-9]|3[01])/\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/cpu(1[6-9]|2[0-9]|3[01])/" }
     ]
    }
   ]
  },
  {
   "title": "IPMI Fan Speeds",
   "type": "graph",
   "description": "Note: Uses REGEX to Parse Fan Names From IPMI Sensor List!",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/fan./" }
     ]
    }
   ]
  },
  { "title": "UPS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 237 } },
  {
   "title": "UPS Load %",
   "type": "graph",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 238 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT last(\"load_percent\") FROM \"apcupsd\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UPS Load" ], "type": "alias" }
      ],
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .01 * $upsmaxwatt" ], "type": "math" },
       { "params": [ "Watts" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current Input V",
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "input_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 7, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UPS Battery %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current Load W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .01 * $upsmaxwatt" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Load Vs. Time Left",
   "type": "graph",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 247 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .01 * $upsmaxwatt" ], "type": "math" },
       { "params": [ "Watts" ], "type": "alias" }
      ],
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Time Left" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Cost",
   "type": "stat",
   "description": "Note:  Uses Variables | Adjust Field  Unit For Your Set UPS Currency Variable As Required!",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Estimated Annual Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "* .01 * $upsmaxwatt/1000*24*$upskwhprice*365.24"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Load kWh",
   "type": "stat",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .01 * $upsmaxwatt/1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost This Year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Annual Cost So Far",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "* .01 * $upsmaxwatt/1000/24*$upskwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Runtime Left!",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 251 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 60000000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "stat",
   "description": "Note: Uses Variables",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Average W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* .01 * $upsmaxwatt" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Daily Cost",
   "type": "stat",
   "description": "Note:  Uses Variables | Adjust Field  Unit For Your Set UPS Currency Variable As Required!",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Daily Cost",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "* .01 * $upsmaxwatt/1000/365.24*$upskwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  }
 ]
}